language: python

matrix:
    include:
        - os: linux
          sudo: required
          python: 3.6
          env: TOXENV=py32
        - os: windows
          python: 3.6
          env: TOXENV=py36
        - os: osx
          language: generic
          env: TOXENV=3.6.2

before_install:
  - ./.travis/osx-setup.sh

install:
  - pip install -r dependencies.txt

script: 
  - cd /Git-Issue
  - python -m pytest